const interests = [
  "WEB_DEVELOPMENT",
  "MOBILE_DEVELOPMENT",
  "BACKEND_DEVELOPMENT",
  "FRONTEND_DEVELOPMENT",
  "FULLSTACK_DEVELOPMENT",
  "GAME_DEVELOPMENT",
  "DESKTOP_DEVELOPMENT",

  "JAVASCRIPT",
  "PYTHON",
  "JAVA",
  "TYPESCRIPT",
  "CSHARP",
  "GO",
  "RUST",
  "PHP",

  "REACT",
  "ANGULAR",
  "VUE",
  "NODEJS",
  "DJANGO",
  "SPRING",
  "DOTNET",
  "FLUTTER",
  "REACT_NATIVE",

  "DATA_SCIENCE",
  "MACHINE_LEARNING",
  "ARTIFICIAL_INTELLIGENCE",
  "BIG_DATA",
  "DATA_ANALYTICS",

  "CLOUD_COMPUTING",
  "DEVOPS",
  "DOCKER",
  "KUBERNETES",
  "AWS",
  "AZURE",
  "MICROSERVICES",

  "SQL_DATABASES",
  "NOSQL_DATABASES",
  "DATABASE_DESIGN",

  "CYBERSECURITY",
  "ETHICAL_HACKING",
  "WEB_SECURITY",

  "UI_UX_DESIGN",
  "WEB_DESIGN",
  "PRODUCT_DESIGN",

  "BLOCKCHAIN",
  "CRYPTOCURRENCY",
  "WEB3",
  "IOT",
  "AR_VR",
  "QUANTUM_COMPUTING",

  "SOFTWARE_ARCHITECTURE",
  "API_DEVELOPMENT",
  "TESTING",
  "AGILE_METHODOLOGIES",

  "LINUX",
  "OPEN_SOURCE",
  "GIT_VERSION_CONTROL",
  "NETWORKING",
];

export default interests;
