/*
  Warnings:

  - The values [WEB_DEVELOPMENT,MOBILE_DEVELOPMENT,BACKEND_DEVELOPMENT,FRONTEND_DEVELOPMENT,FULLSTACK_DEVELOPMENT,GAME_DEVELOPMENT,DESKTOP_DEVELOPMENT,CSHARP,VUE,NODEJS,DOTNET,REACT_NATIVE,DATA_SCIENCE,MACHINE_LEARNING,ARTIFICIAL_INTELLIGENCE,BIG_DATA,DATA_ANALYTICS,CLOUD_COMPUTING,DEVOPS,AWS,MICROSERVICES,SQL_DATABASES,NOSQL_DATABASES,DATABASE_DESIGN,CYBERSECURITY,ETHICAL_HACKING,WEB_SECURITY,UI_UX_DESIGN,WEB_DESIGN,PRODUCT_DESIGN,BLOCKCHAIN,CRYPTOCURRENCY,WEB3,IOT,AR_VR,QUANTUM_COMPUTING,SOFTWARE_ARCHITECTURE,API_DEVELOPMENT,TESTING,AGILE_METHODOLOGIES,OPEN_SOURCE,GIT_VERSION_CONTROL,NETWORKING] on the enum `Interest` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "Interest_new" AS ENUM ('JAVASCRIPT', 'PYTHON', 'JAVA', 'C#', 'C++', 'PHP', 'C', 'TYPESCRIPT', 'RUBY', 'SWIFT', 'KOTLIN', 'GO', 'RUST', 'SCALA', 'R', 'PERL', 'HASKELL', 'LUA', 'DART', 'ELIXIR', 'CLOJURE', 'JULIA', 'MATLAB', 'GROOVY', 'POWERSHELL', 'BASH', 'VBSCRIPT', 'ASSEMBLY', 'FORTRAN', 'COBOL', 'HTML', 'CSS', 'ANGULAR', 'REACT', 'VUE.JS', 'JQUERY', 'BOOTSTRAP', 'SVELTE', 'NEXT.JS', 'NUXT.JS', 'WEBPACK', 'SASS', 'LESS', 'TAILWINDCSS', 'EMBER.JS', 'BACKBONE.JS', 'D3.JS', 'THREE.JS', 'NODE.JS', 'EXPRESS', 'DJANGO', 'FLASK', 'SPRING', 'ASP.NET', 'LARAVEL', 'RAILS', 'FASTAPI', 'NESTJS', 'SYMFONY', 'CODEIGNITER', 'PLAY', 'SINATRA', 'SQL', 'MYSQL', 'POSTGRESQL', 'SQLITE', 'MONGODB', 'REDIS', 'ORACLE', 'SQL-SERVER', 'MARIADB', 'CASSANDRA', 'DYNAMODB', 'FIREBASE', 'ELASTICSEARCH', 'NEO4J', 'COUCHDB', 'INFLUXDB', 'ANDROID', 'IOS', 'REACT-NATIVE', 'FLUTTER', 'XAMARIN', 'KOTLIN-MULTIPLATFORM', 'SWIFTUI', 'CORDOVA', 'IONIC', 'AMAZON-WEB-SERVICES', 'AZURE', 'GOOGLE-CLOUD-PLATFORM', 'DOCKER', 'KUBERNETES', 'TERRAFORM', 'ANSIBLE', 'JENKINS', 'CI/CD', 'HEROKU', 'NGINX', 'APACHE', 'LINUX', 'UBUNTU', 'WINDOWS', 'MACHINE-LEARNING', 'TENSORFLOW', 'PYTORCH', 'PANDAS', 'NUMPY', 'SCIKIT-LEARN', 'KERAS', 'OPENCV', 'NLPROC', 'DEEP-LEARNING', 'COMPUTER-VISION', 'DATA-SCIENCE', 'MATPLOTLIB', 'SCIPY', 'JUPYTER-NOTEBOOK', 'GIT', 'GITHUB', 'REGEX', 'JSON', 'XML', 'REST', 'GRAPHQL', 'GRPC', 'WEBSOCKET', 'OAUTH', 'JWT', 'UNIT-TESTING', 'DEBUGGING', 'ALGORITHMS', 'DATA-STRUCTURES', 'DESIGN-PATTERNS', 'MULTITHREADING', 'ASYNC', 'DEPENDENCY-INJECTION');
ALTER TABLE "User" ALTER COLUMN "interests" TYPE "Interest_new"[] USING ("interests"::text::"Interest_new"[]);
ALTER TYPE "Interest" RENAME TO "Interest_old";
ALTER TYPE "Interest_new" RENAME TO "Interest";
DROP TYPE "public"."Interest_old";
COMMIT;
